spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.99.100:3306/elio?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://34.64.143.149:3306/elio?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: elio1
  output:
    ansi:
      enabled: always
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
    static-path-pattern: /resources/**
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

custom:
  upload-path: /usr/etc/upload/

mybatis:
  mapper-locations: mapper/*Mapper.xml

handlebars:
  prettyPrint: true
  exposeRequestAttributes: false
  exposeSessionAttributes: true
  allowRequestOverride: true
  exposeSpringMacroHelpers: true
  resolver:
    method: true
    field: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    path: logs

server:
  port: 80




# MyBatis 설정 파일을 로드한다.
#mybatis.mapper-locations=mapper/*Mapper.xml

# Mysql 설정
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.99.100:3306/elio?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=elio1

# 콘솔 창에 출력되는 로깅 메세지를 색으로 구분해서 출력
#spring.output.ansi.enabled=always
# 로그 메세지가 저장되는 로그 디렉터리
#logging.path=logs
# logging.level.{패키지 경로}를 통해 로깅 레벨을 결정할 수 있슴
#logging.level.com.tutorial.springboot=DEBUG

# jsp
#server.port=8080
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

# static resource
#spring.mvc.static-path-pattern=/resources/static/**